version: "3.9"
services:
  odoo:
    image: odoo:16
    container_name: odoo
    restart: always
    depends_on:
      - postgres
    environment:
      - HOST=postgres
      - USER=odoo
      - PASSWORD=passwd12345
    ports:
      - 8069:8069
    networks:
      - dclocal-net
    volumes:
    #  - ./data/odoo/odoo.conf:/etc/odoo/odoo.conf
      - ./webdata/odoo/addons:/mnt/extra-addons
    #  - ./webdata/odoo:/var/lib/odoo
  gitea:
    image: gitea/gitea:1.19.0
    container_name: gitea
    restart: always
    depends_on:
      - postgres
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=postgres:5432
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=passwd12345
    ports:
      - 3000:3000
      - 2222:22
    networks:
      - dclocal-net
    volumes:
      - ./webdata/gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
  nextcloud:
    #image: nextcloud:fpm-alpine
    build:
      context: .
      dockerfile: ./docker/Dockerfile-nextcloud
    container_name: nextcloud
    restart: always
    depends_on:
      - postgres
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=passwd12345
    ports:
      - 8081:9000
    networks:
      - dclocal-net
    volumes:
      - ./webdata/nextcloud:/var/www/html
  wordpress:
    #image: wordpress:fpm-alpine
    build:
      context: .
      dockerfile: ./docker/Dockerfile-wordpress
    container_name: wordpress
    restart: always
    depends_on:
      - mariadb
    environment:
      - WORDPRESS_DB_HOST=mariadb
      - WORDPRESS_DB_USER=mdbuser
      - WORDPRESS_DB_PASSWORD=passwd12345
      - WORDPRESS_DB_NAME=wpdb890
      - WORDPRESS_TABLE_PREFIX=wpx_
    ports:
      - 8082:9000
    networks:
      - dclocal-net
    volumes:
      - ./webdata/wordpress:/var/www/html
  nginx-proxy:
    #image: nginx:stable-alpine
    build:
      context: .
      dockerfile: ./docker/Dockerfile-nginx
      args:
        ngx_uid: 82
        ngx_gid: 82
    environment:
      - NGINX_UID=82
      - NGINX_GID=82
    container_name: nginx-proxy
    restart: always
    depends_on:
      - odoo
      - wordpress
      - gitea
      - nextcloud
    ports:
      - 80:80
      - 443:443
    networks:
      - dclocal-net
    volumes:
      - ./data/nginx/conf.d:/etc/nginx/conf.d
      - ./data/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /tmp/acme_challenge:/tmp/acme_challenge
      - ./webdata/:/var/www/html/
      #- ./webdata/wordpress:/var/www/html/wordpress
      #- ./webdata/nextcloud:/var/www/html/nextcloud
  adminer:
    image: adminer:latest
    container_name: adminer
    restart: always
    depends_on:
      - postgres
      - mariadb
    ports:
      - 8080:8080
    networks:
      - dclocal-net
  postgres:
    #image: postgres:15-alpine
    build:
      context: .
      dockerfile: ./docker/Dockerfile-postgres
    container_name: postgres
    restart: always
    environment:
    #  - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=passwd12345
      - POSTGRES_MULTIPLE_DATABASES=gitea:gitea:passwd12345; nextcloud:nextcloud:passwd12345
    ports:
      - 5432:5432
    networks:
      - dclocal-net
  mariadb:
    image: yobasystems/alpine-mariadb
    container_name: mariadb
    restart: always
    environment:
      - MYSQL_USER=mdbuser
      - MYSQL_PASSWORD=passwd12345
      - MYSQL_ROOT_PASSWORD=rtpasswd12345
      - MYSQL_DATABASE=wpdb890
    ports:
      - 3306:3306
    networks:
      - dclocal-net
networks:
  dclocal-net:
    driver: bridge