version: "3.9"
services:
  odoo:
    image: odoo:16
    depends_on:
      - postgres
    environment:
      - HOST=postgres
      - USER=pgdbuser
      - PASSWORD=passwd12345
    ports:
      - 8069:8069
    networks:
      - dclocal-net
    volumes:
      - ./data/odoo:/var/lib/odoo
  gitea:
    image: gitea/gitea:1.19.0
    depends_on:
      - postgres
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=postgres:5432
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=pgdbuser
      - GITEA__database__PASSWD=passwd12345
    ports:
      - 3000:3000
      - 2222:22
    networks:
      - dclocal-net
    volumes:
      - ./data/gitea/data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
  nextcloud:
    image: nextcloud:fpm-alpine
    depends_on:
      - postgres
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=pgdbuser
      - POSTGRES_PASSWORD=passwd12345
      - POSTGRES_DB=nextcloud
    ports:
      - 9000:9000
    networks:
      - dclocal-net
    volumes:
      - ./data/nextcloud:/var/www/html
  wordpress:
    image: wordpress:fpm-alpine
    depends_on:
      - mariadb
    environment:
      - WORDPRESS_DB_HOST=mariadb
      - WORDPRESS_DB_USER=mdbuser
      - WORDPRESS_DB_PASSWORD=passwd12345
      - WORDPRESS_DB_NAME=wpdb890
      - WORDPRESS_TABLE_PREFIX=wpx_
    ports:
      - 9001:9000
    networks:
      - dclocal-net
    volumes:
      - ./data/wordpress:/var/www/html
  nginx:
    #image: nginx:stable-alpine
    build:
      context: .
      dockerfile: ./docker/Dockerfile-nginx
    depends_on:
      - odoo
      - wordpress
      - gitea
      - nextcloud
    ports:
      - 80:80
      - 443:443
    networks:
      - dclocal-net
    volumes:
      - ./data/nginx/conf.d:/etc/nginx/conf.d
      - ./data/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /tmp/acme_challenge:/tmp/acme_challenge
      - ./data/wordpress:/var/www/html/wordpress
      - ./data/nextcloud:/var/www/html/nextcloud
  adminer:
    image: adminer:latest
    depends_on:
      - postgres
      - mariadb
    ports:
      - 8080:8080
    networks:
      - dclocal-net
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=pgdbuser
      - POSTGRES_PASSWORD=passwd12345
    ports:
      - 5432:5432
    networks:
      - dclocal-net
  mariadb:
    image: yobasystems/alpine-mariadb
    environment:
      - MYSQL_USER=mdbuser
      - MYSQL_PASSWORD=passwd12345
      - MYSQL_ROOT_PASSWORD=rtpasswd12345
      - MYSQL_DATABASE=wpdb890
    ports:
      - 3306:3306
    networks:
      - dclocal-net
networks:
  dclocal-net:
    driver: bridge