version: "3.9"
services:
  postgres:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-${DB_TYPE}
      args:
        db_name: ${POSTGRES_DB_NAME}
        db_user: ${DB_USER}
        db_password: ${DB_PASSWORD}
        db_port: ${POSTGRES_PORT}
        db_pgdata: ${POSTGRES_PGDATA_DIR}
    container_name: postgres
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      #- POSTGRES_DB=${POSTGRES_DB_NAME}
      - POSTGRES_MULTIPLE_DATABASES=${ODOO_DB_NAME}:${DB_USER}; ${GITEA_DB_NAME}:${DB_USER}; ${NEXTCLOUD_DB_NAME}:${DB_USER}; ${WP_DB_NAME}:${DB_USER}
      - PGDATA=${POSTGRES_PGDATA_DIR}
    restart: always
    networks:
      - app-net
    volumes:
      - postgres-data:/var/lib/postgresql/data
  mariadb:
    image: yobasystems/alpine-mariadb
    container_name: mariadb
    environment:
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${WP_DB_NAME}
    restart: always
    networks:
      - app-net
    volumes:
      - mysql-data:/var/lib/mysql
    depends_on:
      - postgres
  adminer:
    image: adminer:latest
    container_name: adminer
    restart: always
    ports:
      - ${ADMINER_PORT}:8080
    networks:
      - app-net
    depends_on:
      - postgres
      - mariadb
  odoo:
    image: odoo:16.0
    container_name: odoo
    environment:
      - HOST=postgres
      - PORT=${POSTGRES_PORT}
      - USER=${DB_USER}
      - PASSWORD=${DB_PASSWORD}
    links:
      - postgres
    restart: always
    ports:
      # <Port exposed>:<Port running inside container>
      - ${ODOO_PORT}:8069
    networks:
      - app-net
    volumes:
      - odoo-data:/var/lib/odoo
      - ${ODOO_OUTSIDE_CONFIG}:/etc/odoo/odoo.conf
      - ${ODOO_OUTSIDE_ADDONS}:/mnt/extra-addons
    depends_on:
      - postgres
      - mariadb
  gitea:
    image: gitea/gitea:1.19.0
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=postgres:${POSTGRES_PORT}
      - GITEA__database__NAME=${GITEA_DB_NAME}
      - GITEA__database__USER=${DB_USER}
      - GITEA__database__PASSWD=${DB_PASSWORD}
    links:
      - postgres
    restart: always
    ports:
      - ${GITEA_PORT}:3000
      - ${GITEA_SSH_PORT}:22
    networks:
      - app-net
    volumes:
      - gitea-data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - postgres
      - mariadb
  nextcloud:
    image: nextcloud:26.0-fpm-alpine
    container_name: nextcloud
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${NEXTCLOUD_DB_NAME}
    links:
      - postgres
    restart: always
    ports:
      - ${NEXTCLOUD_PORT}:3000
    networks:
      - app-net
    volumes:
      - nextcloud-data:/var/www/html
      - ${NEXTCLOUD_OUTSIDE_DATA}:/var/www/html/data
    depends_on:
      - postgres
      - mariadb
  wordpress:
    image: wordpress:6.1-fpm-alpine
    #image: ntninja/wordpress-postgresql # use Postgre for WordPress
    container_name: wordpress
    environment:
      - WORDPRESS_DB_HOST=mariadb:${MYSQL_PORT}
      - WORDPRESS_DB_USER=${DB_USER}
      - WORDPRESS_DB_PASSWORD=${DB_PASSWORD}
      - WORDPRESS_DB_NAME=${WP_DB_NAME}
    links:
      - mariadb
    restart: always
    ports:
      - ${WP_PORT}:80
    networks:
      - app-net
    volumes:
      - wordpress-data:/var/www/html
      #- ${WP_OUTSIDE_CONFIG}:/var/www/html/wp-config.php
      - ${WP_OUTSIDE_CONTENT}:/var/www/html/wp-content
    depends_on:
      - postgres
      - mariadb
  # Ref: https://github.com/leangaurav/nginx_https_docker
  nginx-proxy:
    container_name: nginx-proxy
    build:
      context: .
      dockerfile: ./docker/Dockerfile-nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    networks:
      - app-net
    volumes:
      - ${NGX_PROXY_CONFIG}:/config
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /tmp/acme_challenge:/tmp/acme_challenge
networks:
  app-net:
    driver: bridge
volumes:
  postgres-data:
    driver: local
  mysql-data:
    driver: local
  odoo-data:
    driver: local
  gitea-data:
    driver: local
  nextcloud-data:
    driver: local
  wordpress-data:
    driver: local