FROM postgres:15-alpine

ARG db_name
ARG db_user=postgres
ARG db_password=postgres
ARG db_port=5432
ARG db_data=/var/lib/postgresql/data

ENV POSTGRES_DB=${db_name}
ENV POSTGRES_USER=${db_user}
ENV POSTGRES_PASSWORD=${db_password}
ENV PGDATA=${db_data}

EXPOSE $db_port
