FROM postgres:15-alpine

#ARG db_name
#ARG db_user=postgres
#ARG db_password=postgres
#ARG db_port=5432
#ARG db_pgdata=/var/lib/postgresql/data/pgdata

#ENV POSTGRES_DB=${db_name}
#ENV POSTGRES_USER=${db_user}
#ENV POSTGRES_PASSWORD=${db_password}
#ENV PGDATA=${db_pgdata}

COPY ./scripts/create-multiple-postgresql-databases.sh /docker-entrypoint-initdb.d/

RUN chmod +x /docker-entrypoint-initdb.d/create-multiple-postgresql-databases.sh

EXPOSE 5432
