FROM nginx:stable-alpine

ARG ngx_uid
ARG ngx_gid

ENV NGINX_UID=${ngx_uid}
ENV NGINX_GID=${ngx_gid}

RUN apk add shadow && usermod -u ${NGINX_UID} -o nginx && groupmod -g ${NGINX_GID} -o nginx

#RUN mv /etc/nginx/conf.d/default.conf /etc/nginx/conf.d/default.conf.bak
#COPY ./data/nginx/config/nginx.conf /etc/nginx/conf.d/
#COPY ./data/nginx/config/proxy_params /etc/nginx/conf.d/
#COPY ./data/nginx/config /etc/nginx/

RUN mkdir -p /var/www/html/wordpress
RUN mkdir -p /var/www/html/nextcloud
RUN chown -hR ${NGINX_UID}:${NGINX_GID} /var/www/html