FROM nginx:stable-alpine

#RUN mv /etc/nginx/conf.d/default.conf /etc/nginx/conf.d/default.conf.bak
#COPY ./data/nginx/config/nginx.conf /etc/nginx/conf.d/
#COPY ./data/nginx/config/proxy_params /etc/nginx/conf.d/
#COPY ./data/nginx/config /etc/nginx/